AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sam Template
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn:
              Fn::GetAtt:
              - MyAuthFunction
              - Arn
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloFunction
      CodeUri: s3://yinghan-bucket/2faa311313b5541cc66cf675b533bcdc
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /hello
            Method: GET
  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyAuthFunction
      CodeUri: s3://yinghan-bucket/c7b21323f93c1ef9e52a98318af93c16
      Handler: app.authorizer
      Runtime: nodejs12.x
Outputs:
  Region:
    Description: Region
    Value:
      Ref: AWS::Region
  ApiId:
    Description: API ID
    Value:
      Ref: MyApi
  ApiUrl:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/
